# Generated by Django 3.1.4 on 2020-12-23 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_path', models.FileField(upload_to='documents/File/')),
                ('doc_img', models.ImageField(upload_to='documents/File_img/')),
                ('file_name', models.CharField(max_length=30)),
                ('file_type', models.CharField(max_length=30)),
                ('file_desc', models.TextField(max_length=70)),
                ('stu_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='user/picture')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('university', models.CharField(blank=True, max_length=50, null=True)),
                ('carrer', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True)),
                ('studing', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='user/picture')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('university', models.CharField(blank=True, max_length=50, null=True)),
                ('carrer', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True)),
                ('visibility', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesors',
            },
        ),
        migrations.CreateModel(
            name='Post_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=30)),
                ('post_desc', models.TextField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('file_rel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.document')),
                ('user_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post_File',
                'verbose_name_plural': 'Post_files',
            },
        ),
        migrations.CreateModel(
            name='Pay_method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('card_number', models.CharField(max_length=16)),
                ('card_date', models.DateField()),
                ('security_num', models.CharField(max_length=3)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.student')),
            ],
            options={
                'verbose_name': 'Pay_method',
                'verbose_name_plural': 'Pay_methods',
            },
        ),
    ]
